apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-namespace
  namespace: namespace
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
